on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: yupeng123/hello-world-javascript-actions-yp@main
        with:
          who-to-greet: "yupeng"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - run: echo '${{ steps.hello.outputs.time }}'
      - name: My first step
        uses: docker://alpine:3.8
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
          need: Upload-log-file
