name: ci

on: push

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -a

  test:
    runs-on: windows-latest
    steps:
      - run: |
          dir
